// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: maps_any.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TheMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int64Kv map[string]int64  `protobuf:"bytes,1,rep,name=int64kv,proto3" json:"int64kv,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Strkv   map[string]string `protobuf:"bytes,2,rep,name=strkv,proto3" json:"strkv,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TheMap) Reset() {
	*x = TheMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maps_any_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheMap) ProtoMessage() {}

func (x *TheMap) ProtoReflect() protoreflect.Message {
	mi := &file_maps_any_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheMap.ProtoReflect.Descriptor instead.
func (*TheMap) Descriptor() ([]byte, []int) {
	return file_maps_any_proto_rawDescGZIP(), []int{0}
}

func (x *TheMap) GetInt64Kv() map[string]int64 {
	if x != nil {
		return x.Int64Kv
	}
	return nil
}

func (x *TheMap) GetStrkv() map[string]string {
	if x != nil {
		return x.Strkv
	}
	return nil
}

type RetMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg   string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RetMsg) Reset() {
	*x = RetMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maps_any_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetMsg) ProtoMessage() {}

func (x *RetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_maps_any_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetMsg.ProtoReflect.Descriptor instead.
func (*RetMsg) Descriptor() ([]byte, []int) {
	return file_maps_any_proto_rawDescGZIP(), []int{1}
}

func (x *RetMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RetMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_maps_any_proto protoreflect.FileDescriptor

var file_maps_any_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x73, 0x5f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x61, 0x70, 0x73, 0x61, 0x6e, 0x79, 0x22, 0xe8, 0x01, 0x0a, 0x06, 0x54, 0x68,
	0x65, 0x4d, 0x61, 0x70, 0x12, 0x36, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x6b, 0x76, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x70, 0x73, 0x61, 0x6e, 0x79, 0x2e,
	0x54, 0x68, 0x65, 0x4d, 0x61, 0x70, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x6b, 0x76, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x6b, 0x76, 0x12, 0x30, 0x0a, 0x05,
	0x73, 0x74, 0x72, 0x6b, 0x76, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61,
	0x70, 0x73, 0x61, 0x6e, 0x79, 0x2e, 0x54, 0x68, 0x65, 0x4d, 0x61, 0x70, 0x2e, 0x53, 0x74, 0x72,
	0x6b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x72, 0x6b, 0x76, 0x1a, 0x3a,
	0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x6b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x38, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x6b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x32, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x2a,
	0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x73, 0x61, 0x6e, 0x79,
	0x2e, 0x54, 0x68, 0x65, 0x4d, 0x61, 0x70, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x73, 0x61, 0x6e,
	0x79, 0x2e, 0x52, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maps_any_proto_rawDescOnce sync.Once
	file_maps_any_proto_rawDescData = file_maps_any_proto_rawDesc
)

func file_maps_any_proto_rawDescGZIP() []byte {
	file_maps_any_proto_rawDescOnce.Do(func() {
		file_maps_any_proto_rawDescData = protoimpl.X.CompressGZIP(file_maps_any_proto_rawDescData)
	})
	return file_maps_any_proto_rawDescData
}

var file_maps_any_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_maps_any_proto_goTypes = []interface{}{
	(*TheMap)(nil), // 0: mapsany.TheMap
	(*RetMsg)(nil), // 1: mapsany.RetMsg
	nil,            // 2: mapsany.TheMap.Int64kvEntry
	nil,            // 3: mapsany.TheMap.StrkvEntry
}
var file_maps_any_proto_depIdxs = []int32{
	2, // 0: mapsany.TheMap.int64kv:type_name -> mapsany.TheMap.Int64kvEntry
	3, // 1: mapsany.TheMap.strkv:type_name -> mapsany.TheMap.StrkvEntry
	0, // 2: mapsany.Echo.Echo:input_type -> mapsany.TheMap
	1, // 3: mapsany.Echo.Echo:output_type -> mapsany.RetMsg
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_maps_any_proto_init() }
func file_maps_any_proto_init() {
	if File_maps_any_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maps_any_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TheMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maps_any_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maps_any_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maps_any_proto_goTypes,
		DependencyIndexes: file_maps_any_proto_depIdxs,
		MessageInfos:      file_maps_any_proto_msgTypes,
	}.Build()
	File_maps_any_proto = out.File
	file_maps_any_proto_rawDesc = nil
	file_maps_any_proto_goTypes = nil
	file_maps_any_proto_depIdxs = nil
}
