/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqlitedemo;

import java.sql.*;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var con = DriverManager.getConnection("jdbc:sqlite:tutorjoes.db");
        var stmt = con.createStatement();
        ResultSet rs;
        PreparedStatement st;

        String query = "";
        int id, age, choice;
        String name, city;

        var in = new Scanner(System.in);
        var out = new Scanner(System.in);

    }
}
